This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file ./mainthesisUVIC.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file mainthesisUVIC.acn....done (252 entries accepted, 0 rejected).
Sorting entries.....done (2338 comparisons).
Generating output file mainthesisUVIC.acr....done (135 lines written, 0 warnings).
Output written in mainthesisUVIC.acr.
Transcript written in mainthesisUVIC.alg.
